# Lambda function

In [ ]:
x = lambda a : a + 10

print(x(5))

In [ ]:
x = lambda a, b : a * b
print(x(6, 7))

In [ ]:
def myfunc(n):
    return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

## Numpy code along


In [28]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [29]:
## one dimensional array is a vector
a = np.array([5,3,2])

In [30]:
a.shape

(3,)

#### Generate an array with random numbers

In [ ]:
np.random.seed(14)
a = np.random.random((6,2))
a

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [24]:
lst_lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst_lst)
print(d.shape)

(3, 3)


In [26]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Constant arrays

In [31]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [32]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.18628912,  0.01466137, -1.07556947],
       [ 0.64225207, -0.18033671,  0.62030025],
       [ 0.81097433,  0.77793587, -0.23748968]])

In [36]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 5, 8],
       [9, 5, 3],
       [9, 9, 4]])

#### Array Attributes

In [37]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [38]:
a.shape

(6, 3)

In [39]:
a.size

18

In [40]:
a.ndim

2

In [42]:
a.dtype

dtype('float64')

In [44]:
b = np.array([1,3,8])

In [45]:
b.dtype

dtype('int32')

In [46]:
b.astype(np.int8)

array([1, 3, 8], dtype=int8)

In [47]:
b.itemsize

4

In [49]:
c = np.array([1,3,4], dtype="int8") # smaller integers

In [50]:
c.itemsize

1

In [51]:
c = np.array([1,3,4]).astype(np.int8)

In [52]:
c

array([1, 3, 4], dtype=int8)

In [53]:
new_array = np.array([1,2,True])

In [ ]:
new_array

In [ ]:
(new_array).dtype

#### Array indexing

In [54]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [55]:
a[0]

array([0.69646919, 0.28613933, 0.22685145])

In [56]:
a[0,0]

0.6964691855978616

In [57]:
a[0,-1]

0.2268514535642031

In [58]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [59]:
a[0,1:3]

array([0.28613933, 0.22685145])

In [61]:
a[:,:]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

#### Modifying a slice will modify the array

In [62]:
a[0,0]

0.6964691855978616

In [63]:
a[0,0] = 10

In [64]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

#### Boolean indexing

In [65]:
print(a)

[[10.          0.28613933  0.22685145]
 [ 0.55131477  0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


In [66]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [71]:
print(a[bool_idx])
#print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [75]:
np.arange(1,10).shape

(9,)

In [76]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Subarrays return views, not copies!

In [77]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [78]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

array([[0.55131477, 0.71946897],
       [0.9807642 , 0.68482974]])

In [79]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

[[0.         0.71946897]
 [0.9807642  0.68482974]]


[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### Creating copies

In [80]:
a_copy = a.copy()

In [81]:
a_copy

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.        ,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [82]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

[[0.         0.28613933 0.22685145]
 [0.         0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]] 

[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### 3-D arrays

In [ ]:
b = np.random.random((5,2,3))
print(b)

### 4-D arrays

In [ ]:
c = np.random.random((2,3,4,5))
print(c)


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [83]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x**y  # works with *, /, **  element wise 

array([  1,  32, 729], dtype=int32)

Lists do not behave the same way: sum means concatenation

In [84]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [85]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [86]:
print (x + y)

[[ 6  8]
 [10 12]]


In [88]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.        ,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [87]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

[2.09157489 0.37929761 0.40557259]
[3.50433026 0.38085848 0.71550861 0.48811508 0.2987648  0.36531296]


2.0

In [89]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [ ]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

In [ ]:
np.sqrt(squared_deviations.mean())

In [ ]:
new_array = np.array([[1,2],[3,4],[5,6]])

In [ ]:
new_array

In [90]:
rand_array = np.random.random(9)

In [91]:
rand_array

array([0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426,
       0.73799541, 0.18249173, 0.17545176, 0.53155137])

In [93]:
rand_array = rand_array.reshape((3,3))

In [94]:
rand_array

array([[0.34317802, 0.72904971, 0.43857224],
       [0.0596779 , 0.39804426, 0.73799541],
       [0.18249173, 0.17545176, 0.53155137]])

In [98]:
rand_array.T

array([[0.34317802, 0.0596779 , 0.18249173],
       [0.72904971, 0.39804426, 0.17545176],
       [0.43857224, 0.73799541, 0.53155137]])

#### Performance of numpy operations vs lists

In [99]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

1.2916462421417236


In [100]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

0.012000560760498047


#### Concatenate

In [101]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0], [9,9,9]])

In [102]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
second

array([[0, 0, 0],
       [9, 9, 9]])

In [104]:
np.concatenate([first, second])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [9, 9, 9]])

In [105]:
np.concatenate([first, second], axis=1)

array([[1, 2, 3, 0, 0, 0],
       [4, 5, 6, 9, 9, 9]])

In [106]:
one_dim = np.array([1,1,1])

In [109]:
np.vstack([first, one_dim])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

### Transpose

In [110]:
print(first)

[[1 2 3]
 [4 5 6]]


In [111]:
print(first.T)

[[1 4]
 [2 5]
 [3 6]]


#### Splitting arrays

In [112]:
hundred = np.array(range(1,101))

In [113]:
hundred

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [114]:
first_half, second_half = np.split(hundred, [50])

In [115]:
first_half

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [116]:
second_half

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])